
fs::dir_create("inst/www")

fs::dir_create("inst/www/animations")
fs::dir_create("inst/www/content")
fs::dir_create("inst/www/fonts")
fs::dir_create("inst/www/images")
fs::dir_create("inst/www/scripts")
fs::dir_create("inst/www/styles")
fs::file_create("inst/www/README.md")

fs::dir_create("inst/www/content/about")
fs::dir_create("inst/www/content/contact")
fs::dir_create("inst/www/content/faq")
fs::dir_create("inst/www/content/help")
fs::dir_create("inst/www/content/techstack")

fs::file_create("inst/www/content/about/index.qmd")
fs::file_create("inst/www/content/contact/index.qmd")
fs::file_create("inst/www/content/faq/index.qmd")
fs::file_create("inst/www/content/help/index.qmd")
fs::file_create("inst/www/content/techstack/index.qmd")

fs::dir_create("inst/www/fonts/Inter")
fs::dir_create("inst/www/fonts/Roboto")
fs::dir_create("inst/www/fonts/Lato")
fs::dir_create("inst/www/fonts/Raleway")

fs::dir_create("inst/www/images/gmh")
fs::dir_create("inst/www/images/entrata")
fs::dir_create("inst/www/images/noclocks")
fs::dir_create("inst/www/images/shared")
fs::dir_create("inst/www/images/shared/avatars")
fs::dir_create("inst/www/images/shared/placeholders")
fs::dir_create("inst/www/images/shared/icons")
fs::dir_create("inst/www/images/shared/logos")
fs::dir_create("inst/www/images/shared/techstack")
fs::dir_create("inst/www/images/shared/social")
fs::dir_create("inst/www/images/shared/illustrations")

fs::dir_create("inst/www/images/gmh/properties")
fs::dir_create("inst/www/images/gmh/partners")
fs::dir_create("inst/www/images/gmh/icons")
fs::dir_create("inst/www/images/gmh/logos")
fs::dir_create("inst/www/images/gmh/banners")

fs::dir_create("inst/www/images/entrata/banners")
fs::dir_create("inst/www/images/entrata/icons")
fs::dir_create("inst/www/images/entrata/logos")

fs::dir_create("inst/www/images/noclocks/team")
fs::dir_create("inst/www/images/noclocks/icons")
fs::dir_create("inst/www/images/noclocks/logos")
fs::dir_create("inst/www/images/noclocks/banners")
fs::dir_create("inst/www/images/noclocks/favicons")
