DROP SCHEMA IF EXISTS mkt;
CREATE SCHEMA IF NOT EXISTS mkt;

DROP TABLE IF EXISTS mkt.properties;

CREATE TABLE IF NOT EXISTS mkt.properties (
  property_id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  property_name TEXT NOT NULL,
  is_competitor BOOLEAN NOT NULL DEFAULT FALSE,
  gmh_property_id INT,
  portfolio_id INT,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
